title: Stein Thinning
logo: /assets/img/gmm.png
description: >
    Optimally thinning of output from a sampling procedure, such as MCMC. 
    Here the red samples are automatically chosen by Stein Thinning to 
    provide a more accurate approximation to the distributional target, 
    compared with the original MCMC output. <a href="https://arxiv.org/abs/2005.03952">[Read more]</a>
theme: jekyll-theme-minimal
